# Generated by Django 4.2.4 on 2023-08-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predict",
            name="avg_glucose_level",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="predict",
            name="smoking_status",
            field=models.CharField(max_length=30),
        ),
    ]
