# Generated by Django 4.2.4 on 2023-08-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0002_alter_predict_avg_glucose_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predict",
            name="avg_glucose_level",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="predict",
            name="bmi",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
