# Generated by Django 4.2.4 on 2023-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0003_alter_predict_avg_glucose_level_alter_predict_bmi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predict",
            name="gender",
            field=models.CharField(
                choices=[("Male", "MALE"), ("Male", "FEMALE"), ("", "")],
                default="",
                max_length=20,
            ),
        ),
    ]
