# Generated by Django 4.2.4 on 2023-08-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0007_alter_predict_residence_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predict",
            name="gender",
            field=models.CharField(
                choices=[("Male", "MALE"), ("Female", "FEMALE")], max_length=20
            ),
        ),
    ]
